/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recruitmentsystem;

/**
 *
 * @author mahmo
 */
public class Home extends javax.swing.JFrame {
    
    static String User ;
    static int userid;
    /**
     * Creates new form Home
     * @param id
     * @param t
     */
    public Home(int id,String t) {
        initComponents();
        Home.userid = id;
        Home.User = "Admin";
        HandleUI();
    }
    public void HandleUI(){
        //Add the Achivments in the box as the Applicant open the new jframe
        // userlabel.setText("Hello  " + RecrutmentControler.getEmployers().get(userid).getUsername());
        switch (User) {
            case "Employer":
                TrackApplication.setEnabled(false);
                ApplyForJob.setEnabled(false);
                JobOffers.setEnabled(false);
                AddJobIntrest.setEnabled(false);
                DisplayJobOffers.setEnabled(false);
                CreateApplicationBand.setEnabled(false);
                BanUser.setVisible(false);
                PostJobRequests.setVisible(false);
                postlabel.setVisible(false);
                postlabel.setVisible(false);
                PostButton.setVisible(false);
                PostTextField.setVisible(false);
                PostResult.setVisible(false);
                break;
            case "Applicant":
                SendMessage.setEnabled(false);
                PostJob.setEnabled(false);
                RespondApplication.setEnabled(false);
                BanUser.setVisible(false);
                PostJobRequests.setVisible(false);
                SearchCadidatesRadio.setVisible(false);
                SearchApplicationsRadio.setVisible(false);

                break;
            case "Admin":
                TrackApplication.setEnabled(false);
                ApplyForJob.setEnabled(false);
                JobOffers.setEnabled(false);
                AddJobIntrest.setEnabled(false);
                DisplayJobOffers.setEnabled(false);
                CreateApplicationBand.setEnabled(false);
                SendMessage.setEnabled(false);
                PostJob.setEnabled(false);
                RespondApplication.setEnabled(false);
                SearchCadidatesRadio.setVisible(false);
                SearchApplicationsRadio.setVisible(false);
                postlabel.setVisible(false);
                postlabel.setVisible(false);
                PostButton.setVisible(false);
                PostTextField.setVisible(false);
                PostResult.setVisible(false);
                break;
            default:
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchResult = new javax.swing.JTextArea();
        PostTextField = new javax.swing.JTextField();
        postlabel = new javax.swing.JLabel();
        PostButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PostResult = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        DisplayJobOffers = new javax.swing.JButton();
        SendMessage = new javax.swing.JButton();
        EditAccount = new javax.swing.JButton();
        PostJob = new javax.swing.JButton();
        TrackApplication = new javax.swing.JButton();
        SearchCadidatesRadio = new javax.swing.JRadioButton();
        SearchApplicationsRadio = new javax.swing.JRadioButton();
        ApplyForJob = new javax.swing.JButton();
        JobOffers = new javax.swing.JButton();
        AddJobIntrest = new javax.swing.JButton();
        RespondApplication = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Adminlabel = new javax.swing.JLabel();
        BanUser = new javax.swing.JButton();
        PostJobRequests = new javax.swing.JButton();
        CreateApplicationBand = new javax.swing.JButton();
        userlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("PerfectRecruit");

        SearchButton.setText("Search");
        SearchButton.setToolTipText("");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        SearchResult.setColumns(20);
        SearchResult.setRows(5);
        jScrollPane1.setViewportView(SearchResult);

        PostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostTextFieldActionPerformed(evt);
            }
        });

        postlabel.setForeground(new java.awt.Color(0, 51, 255));
        postlabel.setText("Post Achivment");

        PostButton.setText("Post");
        PostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostButtonActionPerformed(evt);
            }
        });

        PostResult.setColumns(20);
        PostResult.setRows(5);
        jScrollPane2.setViewportView(PostResult);

        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Results");

        DisplayJobOffers.setText("Display Job Offers");
        DisplayJobOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayJobOffersActionPerformed(evt);
            }
        });

        SendMessage.setText("Send Job Offer");
        SendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMessageActionPerformed(evt);
            }
        });

        EditAccount.setText("Edit Account");
        EditAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAccountActionPerformed(evt);
            }
        });

        PostJob.setText("Post Job");
        PostJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostJobActionPerformed(evt);
            }
        });

        TrackApplication.setText("Track Application");
        TrackApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrackApplicationActionPerformed(evt);
            }
        });

        SearchCadidatesRadio.setText("Search Cadidates");
        SearchCadidatesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCadidatesRadioActionPerformed(evt);
            }
        });

        SearchApplicationsRadio.setText("Search Applications");

        ApplyForJob.setText("Apply For Job");
        ApplyForJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyForJobActionPerformed(evt);
            }
        });

        JobOffers.setText("Job Offers");
        JobOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobOffersActionPerformed(evt);
            }
        });

        AddJobIntrest.setText("Add job intrest");
        AddJobIntrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJobIntrestActionPerformed(evt);
            }
        });

        RespondApplication.setText("Respond Application");
        RespondApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespondApplicationActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("User");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Applicant");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Employer");

        Adminlabel.setText("Admin");

        BanUser.setText("Ban User");
        BanUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanUserActionPerformed(evt);
            }
        });

        PostJobRequests.setText("Post Job Requests");
        PostJobRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostJobRequestsActionPerformed(evt);
            }
        });

        CreateApplicationBand.setText("Create Applications Band");
        CreateApplicationBand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateApplicationBandActionPerformed(evt);
            }
        });

        userlabel.setText("unknown user");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JobOffers, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddJobIntrest, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(postlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CreateApplicationBand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DisplayJobOffers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TrackApplication, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ApplyForJob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PostJob, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(SendMessage)
                                        .addComponent(RespondApplication, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(BanUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PostJobRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Adminlabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(userlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(297, 297, 297)
                                    .addComponent(SearchButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PostButton)))
                            .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(SearchCadidatesRadio)
                                .addGap(18, 18, 18)
                                .addComponent(SearchApplicationsRadio)))
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton)
                    .addComponent(userlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCadidatesRadio)
                    .addComponent(SearchApplicationsRadio)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(postlabel)
                                    .addComponent(PostButton))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SendMessage)
                                    .addComponent(PostJob))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RespondApplication)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(TrackApplication)
                                .addGap(4, 4, 4)
                                .addComponent(ApplyForJob)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JobOffers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddJobIntrest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DisplayJobOffers)
                                .addGap(6, 6, 6)
                                .addComponent(CreateApplicationBand, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Adminlabel)
                                .addGap(7, 7, 7)
                                .addComponent(BanUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PostJobRequests)
                                .addGap(13, 13, 13))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        String SearchValue = SearchTextField.getText();
         if("Employer".equals(User)){
            if(SearchCadidatesRadio.isSelected() && !SearchApplicationsRadio.isSelected()){
                 SearchResult.setText(RecrutmentControler.getEmployers().get(userid).Search(SearchValue));
            }else if(SearchApplicationsRadio.isSelected() && !SearchCadidatesRadio.isSelected() ){
                String AllBands = "nothing Found";
                for(ApplicationBand s: RecrutmentControler.getEmployers().get(userid).searchApplication(SearchValue)){
                    AllBands +=s.displayApp();
                }
                 SearchResult.setText(AllBands);
            }else{
                SearchResult.setText("No Options are selected or more than one Option is selected ");
            }
        }else if("Applicant".equals(User)){
            SearchResult.setText(RecrutmentControler.getApplicants().get(userid).Search(SearchValue));
        }else{
            SearchResult.setText("Session Error: un identified User");
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void PostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostButtonActionPerformed
        String AchivmentValue = PostTextField.getText();
        PostResult.setText(AchivmentValue);
        RecrutmentControler.getApplicants().get(userid).postAchivment(AchivmentValue);
    }//GEN-LAST:event_PostButtonActionPerformed

    private void PostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostTextFieldActionPerformed

    private void DisplayJobOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayJobOffersActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_DisplayJobOffersActionPerformed

    private void EditAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAccountActionPerformed
        /*AccountForm formobj= new AccountForm();
        AccEdit.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_EditAccountActionPerformed

    private void SearchCadidatesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCadidatesRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchCadidatesRadioActionPerformed

    private void BanUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanUserActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_BanUserActionPerformed

    private void PostJobRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostJobRequestsActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_PostJobRequestsActionPerformed

    private void CreateApplicationBandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateApplicationBandActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_CreateApplicationBandActionPerformed

    private void SendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMessageActionPerformed
        /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_SendMessageActionPerformed

    private void PostJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostJobActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_PostJobActionPerformed

    private void RespondApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespondApplicationActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_RespondApplicationActionPerformed

    private void TrackApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrackApplicationActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_TrackApplicationActionPerformed

    private void ApplyForJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyForJobActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_ApplyForJobActionPerformed

    private void JobOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobOffersActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_JobOffersActionPerformed

    private void AddJobIntrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJobIntrestActionPerformed
         /*Message formobj= new Message();
        formobj.setVisible(true);
        this.setVisible(false);
        this.dispose();*/
    }//GEN-LAST:event_AddJobIntrestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home(userid,User).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJobIntrest;
    private javax.swing.JLabel Adminlabel;
    private javax.swing.JButton ApplyForJob;
    private javax.swing.JButton BanUser;
    private javax.swing.JButton CreateApplicationBand;
    private javax.swing.JButton DisplayJobOffers;
    private javax.swing.JButton EditAccount;
    private javax.swing.JButton JobOffers;
    private javax.swing.JButton PostButton;
    private javax.swing.JButton PostJob;
    private javax.swing.JButton PostJobRequests;
    private javax.swing.JTextArea PostResult;
    private javax.swing.JTextField PostTextField;
    private javax.swing.JButton RespondApplication;
    private javax.swing.JRadioButton SearchApplicationsRadio;
    private javax.swing.JButton SearchButton;
    private javax.swing.JRadioButton SearchCadidatesRadio;
    private javax.swing.JTextArea SearchResult;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton SendMessage;
    private javax.swing.JButton TrackApplication;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel postlabel;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
